const lastConversationsResponse = {
	status: "success",
	result: [
		{
			id: 3,
			username: "Test3",
			email: "test3@gmail.com",
			first_name: "",
			last_name: "",
			last_message: "fhf",
			timestamp: "2022-08-12T08:48:59.837649Z",
			read: false,
			delivered: false,
			msg_sender: "Test5",
			msg_receiver: "Test3",
		},
		{
			id: 4,
			username: "Test2",
			email: "test2@gmail.com",
			first_name: "",
			last_name: "",
			last_message: "test5 sending to test3 part1",
			timestamp: "2022-08-12T08:39:59.294703Z",
			read: false,
			delivered: false,
			msg_sender: "Test5",
			msg_receiver: "Test2",
		},
		{
			id: 2,
			username: "Test4",
			email: "test4@gmail.com",
			first_name: "",
			last_name: "",
			last_message: "test5 sending to test3 part1",
			timestamp: "2022-08-12T08:38:54.365352Z",
			read: false,
			delivered: false,
			msg_sender: "Test5",
			msg_receiver: "Test4",
		},
	],
};
export default lastConversationsResponse;
